<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function helbib_base_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}

/**
 * Implements hook_form_alter
*/
function helbib_base_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'views_exposed_form':
      $form['library']['#options']['All'] = t('Biblioteker');
      $form['submit']['#value']           = t('Vælg');
    break;
    case 'ting_search_form':
      $form['keys']['#title'] = t('Indtast søgeord...');
      $form['keys']['#required'] = FALSE;
      $form['#prefix'] = '<span class="page-header-search-header">'.t('Search').'</span>';
    break;
    case 'user_login_block':
      $form['#prefix'] = '<span class="page-header-login-form">'.t('Log in').'</span>';
    break;
  }
}

