<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function helbib_base_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}

/**
 * Implements hook_form_alter
*/
function helbib_base_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'views_exposed_form':
      $form['library']['#options']['All'] = t('Biblioteker');
      $form['submit']['#value']           = t('Vælg');
    break;
    case 'ting_search_form':
      $form['keys']['#title'] = t('Indtast søgeord...');
      $form['keys']['#required'] = FALSE;
    break;
  }
}

/**
 * Installs and configure tinymce_node_picker module to be enabled on Full HTML 
 * wysiwyg editors.
 */
function helbib_base_update_6001() {

  // Install the tinymce node picker module
  drupal_install_modules(array('tinymce_node_picker'));

  $result = db_query("SELECT w.settings, f.format FROM {wysiwyg} AS w LEFT JOIN {filter_formats} f ON f.format = w.format WHERE f.name = 'Full HTML'");

  $settings_obj = db_fetch_object($result);
  $settings     = unserialize($settings_obj->settings);

  if (!array_key_exists('drupal', $settings['buttons'])) {
    $settings['buttons']['drupal']['nodepicker'] = 1;
    db_query("UPDATE {wysiwyg} SET settings = '%s' WHERE format = %d", serialize($settings), $settings_obj->format);

    drupal_set_message(t('Wysiwyg profile for Full HTML has been saved.'));
  }
}

/**
 * Install and enable helbib_profile_image module, which adds a profile image cck field to the profile 
 */
function helbib_base_update_6002() {
  drupal_install_modules(array('helbib_profile_image'));
}
