<?php
/**
 * @file
 * Helsbib-specific customisations for Panels.
 */

/**
 * Implements hook_ctools_plugin_api()
 */
function helbib_panels_ctools_plugin_api() {
  list($module, $api) = func_get_args();

  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
  elseif ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function helbib_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

include_once 'helbib_panels.features.inc';
